### ISSUE TITLE
"What year was Le wagon Lyon opened ? 2017 !"

### ISSUE THREAD

**Issue by Joupsie** [samuelboulery/easter-hunt#15]
2016

**Comment by Joupsie** [comment]
Enfin, 2016, et le premier batch était en janvier 2017 !

**Comment by LeaLandais** [comment]
create a new issue Rémi with only numbers in your response

**Comment by AnnaGT-LW** [comment]
Well done, you're a true Wagoner 🚂  Now, go back to Slack in your batch channel and fallow the guide 😉
